### ISSUE TITLE
Add uniform_distribution for Stiefel?

### ISSUE THREAD

**Issue by dahong67** [JuliaManifolds/Manifolds.jl#141]
Hi! I'm really excited about this package. I have the following snippet floating around in my code for generating a random point uniform on the Stiefel:

```Julia
struct UnifSt{T<:Integer} <: Sampleable{Matrixvariate, Continuous}
    k::T    # inner dimension
    m::T    # outer dimension
    UnifSt{T}(k::T,m::T) where {T<:Integer} = k > m ? error("k > m") : new(k,m)
end
UnifSt(k::T,m::T) where {T<:Integer} = UnifSt{T}(k,m)

Base.size(d::UnifSt) = (d.m,d.k)
Base.size(d::UnifSt, i) = i::Integer <= 2 ? size(d)[i] : 1
function Distributions._rand!(rng::AbstractRNG, d::UnifSt, A::AbstractMatrix)
    randn!(rng,A)
    F = svd!(A)
    A .= F.U*F.Vt
end
```

and I'd be happy to replace it by using `Manifolds.jl`. ;)

Looking through the `uniform_distribution` code for the sphere, I think I could try adding the Stiefel analogue - it seems it would be largely the same.

Is this something already in the works? I'd be happy to make a pull request! :)

**Comment by sethaxen** [comment]
This would be a very welcome contribution! But first a few questions. There are a few different definitions of uniformity on manifolds. For Stiefel, if I remember correctly, the volume measure and Haar measure (invariant under left and right actions of `O(n)`) when normalized coincide with each other. Is this uniform distribution the same as these? Also, do you have a reference for this technique of drawing random samples?

You might want to take a look at #57, which sketches the future of distributions on manifolds. In particular, it would be nice to know if the sampler coincides with one of the samplers implied by a generic distribution like `Projected`, `Restricted`, or `Retracted`.

**Comment by sethaxen** [comment]
Actually, I answered my own question. Chikuse describes in "Statistics on Special Manifolds" how to sample from the distribution on Stiefel that is uniform in the sense I described. That is equivalent to your implementation:

```
B = A(A'A)^{-1/2} # Chikuse, Section 2.5.1
  = USV'((USV')' USV')^{-1/2} # expand with thin SVD
  = USV'(VSU'USV')^{-1/2} # U has unitary columns, so cancel
  = USV'(VS^2V')^{-1/2} # eigendecomposition, so we bring in the 1/2 power
  = USV'VS^{-1}V' # V is unitary and S is almost always nonzero, so cancel
  = U V'
```
though yours seems to be faster than Chikuse's matrix square root version. So yeah, go ahead and submit a PR!

I think also in the example above `U` is uniformly distributed on the Grassmann manifold of the same size, so with just a little more effort, we can have that uniform distribution too. @kellertuer how does this sound?

**Comment by dahong67** [comment]
Yay! Indeed, Chikuse's nice book was also the reference I used for the above implementation. ;) Apologies for failing to mention it earlier!

I've looked through #57, and think this fits in as a `Projected` distribution - would you agree? If so, does that mean it's already implemented somewhere in a generic way? I'm still getting my head wrapped around the code base, and am wondering what a good starting point for this PR might be.

By the way, the simplification used in the above implementation (described in your derivation) raises a question I had when looking through the `project!` method in the Stiefel code:
https://github.com/JuliaManifolds/Manifolds.jl/blob/master/src/manifolds/Stiefel.jl#L236-L242

Are lines 238-239 and the appearance of `qsinv` and `e.vectors` in line 240 needed for numerical reasons? Should the same be done here?

P.S. I also agree about the Grassmann and would be happy to include it in the same PR. :)

**Comment by sethaxen** [comment]
> Apologies for failing to mention it earlier!

No problem at all.

> I've looked through #57, and think this fits in as a Projected distribution - would you agree? If so, does that mean it's already implemented somewhere in a generic way? I'm still getting my head wrapped around the code base, and am wondering what a good starting point for this PR might be.

It certainly looks to me like the `project` function for `Stiefel` when passed a matrix `A` like above does the same thing as your code. If so, then, yeah, it would qualify as a projection. It could currently be implemented using `ProjectedPointDistribution` with the wrapped distribution being a `Distributions.MatrixNormal(zeros(n, k), Matrix(I, n, n), Matrix(I, k, k))` and the wrapped projection being `project!`. That's also how `uniform_distribution` behaves for the `Sphere`. But you could also implement a special distribution just for this, since you can sample from a `MatrixNormal` with zero mean and identity covariances quite a bit more efficiently than `MatrixNormal` currently allows.

We'll eventually add a `Uniform` distribution that generalizes `Distributions.Uniform` for compact manifolds, as proposed in #57.

> Are lines 238-239 and the appearance of `qsinv` and `e.vectors` in line 240 needed for numerical reasons? Should the same be done here?

Good question! I don't know. Looks like they were added in https://github.com/JuliaManifolds/Manifolds.jl/pull/120. For me, it gives the same result as your code, but yours should be more efficient. I'll let @kellertuer comment on that.

> P.S. I also agree about the Grassmann and would be happy to include it in the same PR. :)

Awesome, thanks! I'm not 100% certain about the math, but if you are, I say go for it.

**Comment by kellertuer** [comment]
Thanks for this nice idea of a PR.
Concerning the question, whether the last lines are necessary … maybe not, I did not really check for efficiency yet, I mainly saw the Matlab implementation ( https://github.com/NicolasBoumal/manopt/blob/b1285317ad95e72dc3a5bf06eb0aed65dcb4ead4/manopt/manifolds/stiefel/stiefelgeneralizedfactory.m#L188 )when working on the generalized Stiefel and as a special case the projection on Stiefel fell out. But since that was just a “side quest” of that PR, I did not investigate, whether this simplification could be done further. thinking about it now, I think it can.

A maybe naive question – I am definitely not an expert on distributions – can your idea be generalized to the `GeneralizedStiefel` and hence to `GeneralizedGrassmann`? With the inner product the volume measure should change – but “just” globally.

**Comment by sethaxen** [comment]
> A maybe naive question – I am definitely not an expert on distributions – can your idea be generalized to the `GeneralizedStiefel` and hence to `GeneralizedGrassmann`? With the inner product the volume measure should change – but “just” globally.

The answer isn't obvious to me without doing some math. I only think we can safely define a uniform distribution here if the volume and Haar measures coincide, which is I think the case for `Stiefel` and `Grassmann` for our metrics(of the embedding). So the question is whether the two still coincide for the generalized case, and if so, how does it change their sampling? My gut says yes, and it will be very similar sampling, now from a matrix normal with the matrix `B` as one of the covariances. But we need to verify. I've only seen generalized Grassmann and Stiefel in manopt's code and the paper they reference: https://arxiv.org/pdf/physics/9806030.pdf. Do you know of other papers that explore their properties or if they go by other names?

**Comment by sethaxen** [comment]
I should note that I don't currently have the bandwidth for more math, so someone else will need to check. 🙂

**Comment by sethaxen** [comment]
> But since that was just a “side quest” of that PR, I did not investigate, whether this simplification could be done further. thinking about it now, I think it can.

https://github.com/JuliaManifolds/Manifolds.jl/blob/e3e05578fa00f8e52b023dc6c53cff8f6406e7d1/src/manifolds/GeneralizedStiefel.jl#L161-L167

In the `Stiefel` case, `B` is the identity matrix. Since `U`'s columns are unitary, `qsinv * e.vectors'` will also just be the identity matrix. It then reduces to @dahong67 's code above, so I think we can just update `project!` for `Stiefel`, and then the sampling will use `project!`.

**Comment by kellertuer** [comment]
> In the `Stiefel` case, `B` is the identity matrix. Since `s.U`'s columns are unitary, `qsinv * e.vectors'` will also just be the identity matrix. It then reduces to @dahong67 's code above, so I think we can just update `project!` for `Stiefel`, and then the sampling will use `project!`.

Ah yes, before the first coffee, I did not see that. So yes, we can just update as you said.

**Comment by dahong67** [comment]
Very interesting discussion! I've created a pull request with a first pass at just the Stiefel case for now. It's implemented as a `ProjectedPointDistribution`. :)

For now, I left the current `project!` method intact, but I agree with you two that the simplified version `U V'` is (mathematically) equivalent. I also don't see any obvious numerical pitfalls here, but I'm also not enough of a numerics expert to be super confident. ;) What do you all think? Happy to go with whatever you prefer!

Regarding `GeneralizedStiefel` and `GeneralizedGrassmann`, I would also need to think/study some more. Added to the list of potential todos!

Perhaps more pressing (I'd guess) is thinking through the complex-valued case. What I have is just for the real Stiefel manifold.
