### ISSUE TITLE
Add overloads for Base.in

### ISSUE THREAD

**Issue by sethaxen** [JuliaManifolds/Manifolds.jl#158]
The following overloads would be nice for syntactic convenience:

```julia
Base.in(M::Manifold, p) = is_manifold_point(M, p)
Base.in(TS::TangentSpaceAtPoint, X) = is_tangent_vector(TS.fiber.manifold, TS.point, X)
```

e.g. a user could write `[1, 0, 0] ∈ Sphere(2)` or `[0.5, 0.5, 0.5] ∈ ProbabilitySimplex(2)`

**Comment by kellertuer** [comment]
Should be documented and implemented within `ManifoldsBase` – but it's a very neat idea!

**Comment by mateuszbaran** [comment]
Nice idea! The second method, though, can't currently be implemented in `ManifoldsBase` (it doesn't have `TangentSpaceAtPoint`, although it perhaps should be in `ManifoldsBase`).

**Comment by sethaxen** [comment]
> Nice idea! The second method, though, can't currently be implemented in `ManifoldsBase` (it doesn't have `TangentSpaceAtPoint`, although it perhaps should be in `ManifoldsBase`).

Perhaps. Though that would require fibers and a few other things being migrated over, right? This method is more for completeness, `TangentSpaceAtPoint` is a bit long to write out, and one might as well call `is_tangent_vector`. Where I would see it being useful is if one wanted to check many vectors against a tangent space, and then they would create one of these and then use `in` many times for brevity.

**Comment by mateuszbaran** [comment]
It wouldn't be that much to migrate. Just `VectorBundleFibers`, `VectorSpaceAtPoint` and a few constants and methods. I think this should be done at some point anyway (although it could wait until we see how vector bundles should interact with bases).

**Comment by sivapvarma** [comment]
I would like to take this up. I like the idea behind the project and it would be cool to have all of manopt functionality in a Julia package.

What is the current consensus on what should be moved and add to `ManifoldsBase`.

**Comment by kellertuer** [comment]
There's https://github.com/JuliaManifolds/Manopt.jl which moved to using ManifoldsBase recently. It will cover Swarm-Optim and LRBFGS soon(ish), too.

**Comment by sivapvarma** [comment]
My idea was to start by adding the overloads seth mentioned in this issue to ManifoldsBase.

Since the discussion above points to others things that should be moved like `VectorBundleFibers`, `VectorSpaceAtPoint`, I want to see if there is a clear consensus on what should be moved from here to ManifoldsBase

**Comment by kellertuer** [comment]
Maybe
* the TangentBundle/VEctorBundle stuffif it's code mature and used enough
* the MatricManifold part if necessary and mature and used enough

**Comment by mateuszbaran** [comment]
At this point there is nothing that can easily be moved to ManifoldsBase. There are a few things that are planned (like that vector bundle stuff) but it's not mature enough yet. `MetricManifold` is a tough one because it has a few dependencies and isn't mature enough either. I would recommend developing new stuff in Manifolds.jl unless you need it for compatibility with another package.
