### ISSUE TITLE
How to model different representations for the same manifold?

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manifolds.jl#218]
For a few manifold there are different representations for points and tangent vectors available. How do we want to model those?

Surely for the `FixedRandManifold` where we have to store two matrices or something, we have different `<:MPoint` and `<:TVector` types.

But for example for `Hyperbolic(n)` there are
* the hyperboloid model (vector of length d+1)
* the Poincaré half-plane model (vector of length d)
* the ball model (vector of length d)

With the first being the default that is currently implemented we can now do
* types for the other two. Is that inefficient?
* look ad the dimension and the vector length in ach function – I think _that_ is inefficient
* do maybe a `ManifoldFormat` wrapper for manifolds? This would be similar to ValidationManifold or EmbeddedManifold, i.e. transparent and such but would trigger other exp/log/... calculations for arrays (then instead of Points)?

What do you think?

I am somehow a little in favour of the third variant, but surely conversion between representations can be done for variant 1 and 3 easily.

**Comment by mateuszbaran** [comment]
At the moment it's basically up to a specific manifold how does it want to represent points and tangent vectors. We already have a few different solutions, for example matrices and `ProductRepr` for `SpecialEuclidean`, two representations on product and power manifolds etc. So variant 1 is already quite widely used. Variant 2 doesn't look convincing. As for variant 3, I'm not sure how exactly `ManifoldFormat` is supposed to work since each manifold has different possible representations. In the case of `Hyperbolic`, the manifold type itself could for example take additional parameter that describes which representation is used.

Additionally, since Julia 1.5, wrapping points or vectors in `struct`s is essentially free (performance-wise) so it opens even more possibilities.

**Comment by kellertuer** [comment]
Then I would prefer structs, since storing the format in the manifold is something I am not that much in favour of.
