### ISSUE TITLE
Constructor for Stiefel failed. (Follow docs string)

### ISSUE THREAD

**Issue by qiyang-ustc** [JuliaManifolds/Manifolds.jl#328]
I just follow the docs string for Stiefel
```
julia> using Manifolds
julia> Stiefel(4,4;field = ℝ)
ERROR: MethodError: no method matching Stiefel(::Int64, ::Int64; field=ℝ)
Closest candidates are:
  Stiefel(::Int64, ::Int64) at /Users/yangqi/.julia/packages/Manifolds/x51bQ/src/manifolds/Stiefel.jl:36 got unsupported keyword argument "field"
  Stiefel(::Int64, ::Int64, ::AbstractNumbers) at /Users/yangqi/.julia/packages/Manifolds/x51bQ/src/manifolds/Stiefel.jl:36 got unsupported keyword argument "field"
Stacktrace:
 [1] top-level scope at REPL[3]:1

julia> Stiefel(4,4)
Stiefel(4, 4, ℝ)
```

Maybe it would be helpful to update docs string for Stiefel

**Comment by kellertuer** [comment]
Thank you for your input. I noticed a minor, though important difference, see

https://juliamanifolds.github.io/Manifolds.jl/latest/manifolds/stiefel.html#Manifolds.Stiefel

The documentation says
```Julia
Stiefel(4,4, field = ℝ)
```

(note the comma after the second 4), so `field` is an optional positional argument and not a keyword argument. Using

```julia-repl
julia> Stiefel Stiefel(4, 4, ℝ)
```

works just fine.

This is a little inconsistent, since for Euclidean (or any other manifold that can have an arbitrary number of inputs) the `field` actually _is_ a keyword argument. But for manifolds with a fixed number of parameters, like Stiefel with its 2, it is a positional optional argument.


...unless I missed a typo somewhere, so if you can point me to where a `;` is actually used, I can sure update that.

**Comment by kellertuer** [comment]
If you have further questions or remarks on this point, feel free to reopen this issue.
