### ISSUE TITLE
Test on Rotations(2) only has 1 Degree of Freedom?

### ISSUE THREAD

**Issue by dehann** [JuliaManifolds/Manifolds.jl#352]
https://github.com/JuliaManifolds/Manifolds.jl/blob/4711e6b570b7f6e95ebd10818af9619696f1c74c/test/groups/special_euclidean.jl#L18

Should that not be a single rotation DOF (angle), rather than two for `n=2`?
```julia
ω = [[1.0,], [2.0,], [3.0,]]
```

The others in same test seem correct with `n=3` having 3 DOF, and `n=4` having 6 DOF.

API E.g.:
```julia
Rn = Rotations(n)
x = Matrix(I, n, n)
hat(Rn, x, [2.0; 9999.0])
# 2×2 Matrix{Float64}:
#  0.0  -2.0
#  2.0   0.0
```

**Comment by kellertuer** [comment]
Thanks for noticing. Actually the `hat` function is quite tolerant to its input, and

```julia
hat(Rn, x, 2.0)
hat(Rn, x, [2.0,])
```

give the same result, so the test should have the `ω` as you mentioned, but then returns the same result.

So in short: Just our test is wrong and should be fixed.

**Comment by dehann** [comment]
All good thanks, I'm looking around to find the right point/algebra/group element data formats since the docs only list function calls.  E.g. When is it a tuple / array / ProductRepr / ProductArray etc.  Tests are next best place to look.  Thanks!

**Comment by kellertuer** [comment]
Oh, sorry for that. Currently our philosophy is as follows
* the documentation should provide the mathematical formula.
* the types should be quite loose (to be compatible to any type that might “come around”)

I hope that the documentation (mathematically) also helps to see which types are necessary. For Rotations there is no product manifold, to `ProductRepr`/`ProductArray` are not the right types. It is intended to anything that is of matrix type, so tuples should not work I think.

For example the generic one https://juliamanifolds.github.io/Manifolds.jl/latest/interface.html#ManifoldsBase.hat-Tuple{Manifold,Any,Any} just documents that it maps from the coordinates to a tangent vector (which is actually the same as `get_vector`)

so it should call https://github.com/JuliaManifolds/Manifolds.jl/blob/4711e6b570b7f6e95ebd10818af9619696f1c74c/src/manifolds/Rotations.jl#L296
as you can see here
https://github.com/JuliaManifolds/ManifoldsBase.jl/blob/98e5c87da14555584f54321f8902cc82cbb17f98/src/bases.jl#L618

The `hat`/ `vee` functions are not the right names for all manifolds, that's why in general we use `get_vector`/`get_coordinates`.
Then we are at

https://github.com/JuliaManifolds/Manifolds.jl/blob/4711e6b570b7f6e95ebd10818af9619696f1c74c/src/manifolds/Rotations.jl#L287-L339

But you are right, there is not much math in there

https://juliamanifolds.github.io/Manifolds.jl/latest/manifolds/rotations.html#ManifoldsBase.get_vector-Tuple{Rotations,Vararg{Any,N}%20where%20N}

Feel free to do a PR to make the Test also semantically correct.

If you see a way to improve the documentation, feel free to do that in the same PR as well or ask here for details and I can maybe improve the documentation as well.

**Comment by dehann** [comment]
That helps, thanks.  I do want to help at least with a PR on the Manifolds.jl docs, and think the main thing would just be one or two "Getting Started" tutorials.  I'll send along as soon as I have made it through the learning curve, and will then try capture the lessons accordingly in a concentrated PR (also connects back to the previous discussions too).  It will take a bit of time for me to get through everything since we moving the ApproxManifoldProducts.jl / IncrementalInfererence.jl packages to depend heavily on Manifolds.jl -- so I'm doing some careful planning this side on how, what, where.  

Thanks again for the help!

**Comment by kellertuer** [comment]
Just as a short followup, feel free to also open an issue if you have a good idea for a tutorial.

For now we just have one, i.e. how to implement a manifold 

https://juliamanifolds.github.io/Manifolds.jl/latest/examples/manifold.html

Sure there are more topics one can cover, I just did not yet have a good story for another one.
