### ISSUE TITLE
Getting point size / representation_size

### ISSUE THREAD

**Issue by Affie** [JuliaManifolds/Manifolds.jl#363]
I'm trying to understand `representation_size`
What I need to do is pre-allocate a vector to store points on a manifold and I found `representation_size`.

It makes sense with `SpecialOrthogonal`, however, I would expect a 2x3 matrix or a 3x3 affine matrix  with `SpecialEuclidean(2)`  

```julia
julia> representation_size(TranslationGroup(2))
(2,)

julia> representation_size(SpecialOrthogonal(2))
(2, 2)

julia> representation_size(SpecialEuclidean(2))
(6,)
```

**Comment by kellertuer** [comment]
The `representation_size(M)` is – as you noticed, for allocating memory (so it is especially different from `manifold_dimension` for example. One problem one might habe with `representation_size()` that it does not allow for arbitrary manifolds to allocate; see `FixedRankMatrices` where it returns `(m,n)` the size of the matrix but the storage is actually in SVD form. Usually you can use either `allocate` or `allocate_result` for, this especially takes into account that the type might change; the most prominent example is again `FixedRankMatrices` and then the function `log` where you get `M` and two `SVDMPoint`s but for the result a `UMVTVector` has to be allocated. So `allocate_result` is implemented for `M`, a function `f` and the arguments of the function `f`.

Note also that if you just have the manifold there might also be other representations then the default size (see Hyperbolic), where `representation_size` returns the size of the default representation.
 
to your examples
* `TranslationGroup`  is a group on `Euclidean(2)`, so that's where the `(2,)` comes from
* `SpecialOrthogonal` is a group on `Rotations(2)` so it's `(2,2)` matrices

Then maybe for `M=SpecielEuclidean(2)` matrix it might help to look at its type ( a little verbose):
```
GroupManifold{ℝ, ProductManifold{ℝ, Tuple{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}}}, Manifolds.SemidirectProductOperation{RotationAction{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}, LeftAction}}}`
```
and for the `ProductManifold` the default representation is `ProductRepr`, which internally stores the parts separately. So it is stored as a matrix and a vector. This means, however, that there is no representation size (what should it be if you have two components?) so we return the sum of the elements as a vector. So while it is represented as a `(2,2)` matrix and a `(2,)` vector, the (default - see above) representation size is the vectorized and then concatenated result of both, so a `(6,)` vector.

Example.
```julia
julia> p = ProductRepr([1.0 0.0; 0.0 1.0], [2.0, 3.0])
ProductRepr with 2 submanifold components:
 Component 1 =
  2×2 Matrix{Float64}:
   1.0  0.0
   0.0  1.0
 Component 2 =
  2-element Vector{Float64}:
   2.0
   3.0
```

Oh, and while explaining I found a not yet implemented thing, namely that `getindex` is transparently acting on decorators, so `p[M,1]` to access the first component does not yet work, but
`p[M.manifold, 1]` already does, so in that sense you can even abstractly access the components (and for group manifolds maybe soon, too).

One thing we _could_ to is an `q=allocate(M,p)` that gives you an “empty” `q` you can then fill with your data.

**Comment by mateuszbaran** [comment]
Yes, `representation_size` is the right tool for that _if_ points on your manifold are represented by normal arrays; otherwise it's not much help.

If you need to have a vector of points on `SE(2)` then... I'd advise waiting a couple days until I make a new variant of `PowerManifold` nesting (I meant to do that for months but postponed it because I didn't need it personally).

**Comment by mateuszbaran** [comment]
Hm, it might not be quite that easy. For the best performance, the best thing to do would be to have something like `a = [ProductRepr(SA[1.0, 0.0], SA[1.0 0.0; 0.0 1.0]) for _ in 1:5]` and then in the product manifold replace entire `ProductRepr` at once when mutation is needed. I'd be quite fast since such `ProductRepr`s are `isbits` and stored inline in that vector. This is the easy part and what I meant to do.

The problem is that writing to that vector `a` would still require (currently, this can be gradually amended) making a heap-allocated temporary. Depending on how much writing to `a` you want to perform this may or may not be acceptable. 

What @kellertuer suggested doesn't require allocation of temporaries when writing but then end up with lots of object all around the heap. That may be OK, you can try that (I'd just advise replacing normal arrays with `MArray` from StaticArrays.jl), and then we can work on improving performance.

I know this is a bit much to take at once but we do care about flexibility of point and tangent vector representations. Each one has different advantages so it isn't possible to just recommend one thing. Also, some things are definitely possible within our interface, though we just didn't do them yet.

**Comment by Affie** [comment]
Thanks for the feedback. Currently, I'm still learning and trying to find the best way to move forward without breaking too much on our side. 

So far I'm thinking of having a default point representation of a Static Array of the size of `representation_size` for each component. Thanks, @kellertuer for explaining that. So the  `a = [ProductRepr(SA[1.0, 0.0], SA[1.0 0.0; 0.0 1.0]) for _ in 1:5]` approach, but created based on the manifold provided by a user.
In our case I'm also thinking of having a way of overwriting the default for users to provide their own types, for instance, one might want to rather use `RotMatrix` from Rotations.jl. That will likely go in here: https://github.com/JuliaRobotics/DistributedFactorGraphs.jl/blob/db03bf7188df2f0ea9495de3609301d548fc0048/src/services/DFGVariable.jl#L88-L119 (It needs some cleaning up, but it is already starting to use Manifolds.jl)

I think I got the answers I was looking for so closing this, thanks again.
