### ISSUE TITLE
Do not assume that there is no memory aliasing between output of mutating functions and their input arguments.

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#393]
It can lead to hard-to-find bugs, see #392 .

**Comment by kellertuer** [comment]
I agree, the should not assume that.
But this is phrased quite vague – should we add the test I did generally to `test_manifold` to have this in mind?

**Comment by mateuszbaran** [comment]
It's a bit vague because I'm not sure what exactly should be done. Checking that all functions on all manifolds correctly handle aliasing solves this issue but it would add a relatively long time to each CI run.

**Comment by kellertuer** [comment]
It would not be _all_ functions, but sure, epx/log/retract/inverse_retracte/vector_transport_* at least.

**Comment by kellertuer** [comment]
So lets make the list precise

* `embed!`
* `exp!`
* `inverse_retract`
* `log!`
* `mid_pont!`
* `project!`
* `retract!`
* `vector_transport_to!`
* `vector_transport_direction!`
* `vector_transport_along!` (maybe not since we do not have good generic tests until now I think)

I think we do not have to check `zero_vector!`. I am not sure about `pole_ladder!` and `shields_ladder!` since they are generic in `ManifoldsBase`. We could introduce a parameter in `test_manifold` to activate them?

**Comment by mateuszbaran** [comment]
Thanks for the list, checking them makes sense. A parameter in `test_manifold` that activates them makes sense.
