### ISSUE TITLE
StackOverflowError in manifold_dimension(Unitary(1,ℍ))

### ISSUE THREAD

**Issue by Affie** [JuliaManifolds/Manifolds.jl#510]
Hi, I started experimenting with Unitary for quaternions and came across this error. 
I also wanted to see how `get_coordinates` and `get_vector` worked, but couldn't get them to work.
It can be low priority from my side as we use SO(3), but just wanted to let you know. 
```julia
julia> M = Unitary(1,ℍ)
Unitary(1, ℍ)

julia> manifold_dimension(M)
ERROR: StackOverflowError:
Stacktrace:
 [1] manifold_dimension(M::UnitaryMatrices{1, ℍ}) (repeats 79984 times)
   @ ManifoldsBase ~/.julia/packages/ManifoldsBase/SWdl9/src/decorator_trait.jl:4
```

**Comment by mateuszbaran** [comment]
Sorry, I didn't check that -- I will take a look at it later today.

**Comment by kellertuer** [comment]
Ah that might just be a dispatch missing. Can you maybe post what is not working on the `get_ooordinates`/`get_vector` side?

**Comment by mateuszbaran** [comment]
@kellertuer this seems to be actually not implemented. `get_coordinates` doesn't work at all.

**Comment by kellertuer** [comment]
Maybe, I do not remember, I mainly took over what was in the previous PR.

**Comment by mateuszbaran** [comment]
Manifolds.jl 0.8.23 should have this resolved. Feel free report if there are any further problems :slightly_smiling_face: .

**Comment by Affie** [comment]
Thanks, I tried and thought I'd just mention one thing that caught me with `get_coordinates` (it can perhaps help someone in the future).

I didn't know that the basis also needed the number system, so I tried this:
```julia
get_coordinates(M, p, X, DefaultOrthonormalBasis())
ERROR: MethodError: no method matching similar(::Quaternions.QuaternionF64, ::Type{Quaternions.QuaternionF64}, ::Int64)
Closest candidates are:
  similar(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{N}}, ::Type{ElType}, ::Any) where {N, ElType} at ~/.julia/juliaup/julia-1.7.3+0.x64/share/julia/base/broadcast.jl:212
  similar(::Base.Broadcast.Broadcasted{Base.Broadcast.ArrayConflict}, ::Type{ElType}, ::Any) where ElType at ~/.julia/juliaup/julia-1.7.3+0.x64/share/julia/base/broadcast.jl:217
  similar(::AbstractArray, ::Type{T}, ::Union{Integer, AbstractUnitRange}...) where T at ~/.julia/juliaup/julia-1.7.3+0.x64/share/julia/base/abstractarray.jl:785
  ...
Stacktrace:
  [1] allocate(::Quaternions.QuaternionF64, ::Type, ::Int64)
    @ ManifoldsBase ~/.julia/packages/ManifoldsBase/4j8vE/src/ManifoldsBase.jl:62
```
Instead of this that works:
```julia
get_coordinates(M, p, X, DefaultOrthonormalBasis(ℍ))
```

I don't know if I used `vee` correctly, but it might have the same basis `ℍ` issue that caught me.

**Comment by mateuszbaran** [comment]
Right, that's a not particularly intuitive design choice. The number system in `DefaultOrthonormalBasis` indicates what number should be used for tangent vectors spanning the basis. For example by default it looks for real-vector basis, so in the case of `Unitary(1, ℍ)` you would get a vector that is just the number 1.0 and coefficients would be single quaternions, for example `Quaternion(0.0, 1.0, 2.0, -1.0)`. I haven't implemented that because it doesn't look particularly useful. On the other hand, the quaternionic basis has quaternionic-coordinate vectors `Quaternion(0.0, 1.0, 0.0, 0.0), Quaternion(0.0, 0.0, 1.0, 0.0), Quaternion(0.0, 0.0, 0.0, 1.0)` and three real number coordinates.

I'm not sure which thing `vee` and `hat` should use in this case. Any ideas @kellertuer @sethaxen ?

**Comment by kellertuer** [comment]
I have no experience with `vee` and `hat` and can not comment on what would be the right thing here. I usually prefer real coefficients (and the Quaternionic basis), but that is just my personal preference.
