### ISSUE TITLE
Add the extrinsic mean estimator

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manifolds.jl#77]
It's just the mean in the ambient space and point projection. Not a particularly good estimator but it is fast and simple.

**Comment by sethaxen** [comment]
This would be good to have. Although currently we don't denote manifolds that are implemented as an embedded manifold (i.e. with coordinates of the embedding) in any special way. Perhaps we need a function like `ambient_manifold` that errors by default and otherwise returns the ambient manifold. Then the extrinsic mean is something like `extrinsic_mean(M, xs) = project_point(M, mean(ambient_manifold(M), xs))`.

It _might_ be worth having a version that returns the point in the ambient space and the projected point, as at least in the spherical case (von Mises-Fisher), the distance of the unprojected mean from the projected mean informs the variance of the distribution. Perhaps this will generalize for other `Restricted` distributions. But I'd hold off on that more general version until we know it will be generally useful.

**Comment by sethaxen** [comment]
It's worth noting that in the von Mises-Fisher case, this is a maximum likelihood estimator of the modal point `μ`.

**Comment by kellertuer** [comment]
I think a nice feature to have is a decorator pattern (like the default metric) that indicates that a manifold is an embedded one, maybe with functions like

* ìs_embedded(M)`,
* `is_isometrically_embedded(M)` if the embedding is isometric
* `embed(M,x)` returns the representation of `x` in the embedding (if that's different from the internal data structure, so in a lot of cases this might just be the identity
* `embedded_manifold(M)` returns the manifold `M` is embedded into

And we should then maybe have a fallback if the manifold is not embedded or projection is not possibel (for example for `SymmetricPositiveDefinite`, the set of matrices is open in the embedding, so there is no projection) – to provide a better error message then “not implemented”.

**Comment by mateuszbaran** [comment]
Adding a few functions related to embedding is a good idea. I can add `is_embedded` and `is_isometrically_embedded` and `embedded_manifold` along with the extrinsic mean (although we don't currently have Lorentzian manifolds for the hyperbolic space but it should be easy to add). `embed` would be useful as well but using it consistently across the whole library would take some work.

**Comment by kellertuer** [comment]
Yes, the `embed` will be a little bit of work, but starting with the others fist is a good idea, I think.
